# Author: Mr. Sohamm Gurav
# Project: Kubernetes Pod Deployment with Automatic Scaling

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sohamm-app
  labels:
    app: sohamm-app
    author: "Sohamm Gurav"
spec:
  replicas: 2  # Initial number of pods
  selector:
    matchLabels:
      app: sohamm-app
  template:
    metadata:
      labels:
        app: sohamm-app
    spec:
      containers:
      - name: sohamm-container
        image: nginx  # Replace with actual application image
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"   # Requests 0.2 CPU
            memory: "256Mi"
          limits:
            cpu: "500m"   # Maximum 0.5 CPU
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: sohamm-app-service
spec:
  selector:
    app: sohamm-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Change to LoadBalancer for external access

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sohamm-app-hpa
  labels:
    author: "Sohamm Gurav"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sohamm-app
  minReplicas: 2      # Minimum 2 pods
  maxReplicas: 10     # Maximum 10 pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # Scale when CPU exceeds 60%
